#!/bin/bash  
set -e  

# Copy motor_upgrade files  
cp -r ../usr/motor_upgrade/* /usr/  

# Copy shared libraries  
cp ../usr/motor_upgrade/ota_lib/*.so /usr/lib/  

# Copy executable  
cp ../usr/motor_upgrade/ota_lib/otafifth_demo /usr/bin/  
cp ../usr/motor_upgrade/can-app   /usr/bin 

# Set permissions for the executable  
chmod 777 /usr/bin/otafifth_demo 
chmod 777 /usr/motor_upgrade/run.sh
chmod 777 /usr/bin/can-app

exit 0
