#!/bin/bash
set -e

# Define the variables for directories and files to be removed
MOTOR_UPGRADE_DIR="/usr/motor_upgrade"
OTA_LIB_DIR="/usr/lib/ota_lib"
EXECUTABLE="/usr/bin/otafifth_demo"
rm /usr/bin/can-app

# Stopping a service if necessary (example, replace with your actual service name)
# systemctl stop your_service_name

# Removing the copied files and directories
if [ -d "$MOTOR_UPGRADE_DIR" ]; then
    rm -rf "$MOTOR_UPGRADE_DIR"
fi

if [ -d "$OTA_LIB_DIR" ]; then
    rm -rf "$OTA_LIB_DIR"
fi

if [ -f "$EXECUTABLE" ]; then
    rm "$EXECUTABLE"
fi

# Exit with status 0 indicating success
exit 0